### ISSUE TITLE
x0.at down?

### ISSUE THREAD

**Issue by axm2** [Rouji/single_php_filehost#1]
This is probably not the best channel to reach you, but I didn't know of any better one, are you still supporting x0.at?

**Comment by Rouji** [comment]
Yep, sorry about that! x0.at is definitely still a thing and still very much supported!
We just had a #catastrophicfailure a few days ago, with *both* of the two HDDs in the server kicking the bucket pretty much simultaneously, while SMART was reporting no problems whatsoever...

It's now mostly up and running again, although files uploaded before the crash are still restoring from backup. Could take another day or two, but I don't think we've lost too many files (maybe about half a day's worth?)

Sorry again for the downtime!

**Comment by sergeevabc** [comment]
@Rouji, what has happened to ~500 KiB file at cap.xJY/ta.0x//:sptth?
It was expected to be available for 359 days¹, but was removed in less than a month. 

¹ 10+(360-10)*(1-(0.5/1024))^2

**Comment by Rouji** [comment]
@sergeevabc Hmm, not sure. Might've triggered one of the new spam/malware filtering things or something. I'll have a look at it.

Btw. you can just send me a mail (root@x0.at) if you're worried about privacy or your link getting scraped or something

**Comment by Rouji** [comment]
@sergeevabc Sorry I didn't quite recognise the reversed filename before, but I deleted that file on purpose, because it was causing rather a large amount of hits on the server. 

Someone was actually kind enough to contact and inform me it was "antizapret's censorship circumvention service proxy auto configuration", so not actually a bad thing at all.
Now, I'm all for anti-censorship, but apparently Windows is braindead enough to not ever cache that config and re-downloads it **all the bloody time**. For the person reaching out to me, who hosts it as well, it's apparently gotten as bad as a constant 200mbit/s of traffic just from that...

**Comment by sergeevabc** [comment]
@Rouji, thank you for a quick and thorough reply. Consider adding some warning about how many hits is too much in case somebody might be looking for a place to host a viral meme or clip or something like that.

**Comment by Rouji** [comment]
@sergeevabc I wouldn't mind a "viral meme" causing a bunch of traffic. What I do mind is the same host repeatedly downloading the same file all the time because you're using broken MS software. 

I could restore the file and just ban the shitty MS client that does that, if you'd prefer that(?)

**Comment by sergeevabc** [comment]
@Rouji, the past is the past, what’s done is done, let bygones be bygones. Actually, that file was meant to be downloaded once and then used from a local drive in order to avoid overloading, but some users ignored that.
